import {Title } from '@/components';

export const metadata = {
    title: '00000',
    description: 'Generated by create next app',
  }

async function getData(context) {
    const res = await fetch(`${process.env.API}/news/getNewsBySlug/${context}`);
    console.log('constt',context)
    return res.json()
}

const PageSlugNews = async ({ params }) => {
    const detailNews = await getData(params['slug-news'])
    console.log(params['slug-news'], detailNews)
    return (
        <>
            <div className="bg-light-pink py-5 mb-4">
                <Title className="text-3xl font-bold">tin tức</Title>
            </div>
            <div className='py-16 px-28'>
                <h4 className='text-2xl'>{detailNews.title}</h4>
                <div className='text-base'>{detailNews.slug}</div>
            </div>
        </>
    )
}

export default PageSlugNews